name: 'Hello World654'
description: 'Greet someone'
inputs:
  GREET: 
    description: 'Greeting from environment variables'
    required: true
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: |
         chmod 755 ${{ github.action_path }}/goodbye.sh
         wget https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh?token=AHILVH7YY7DVETVRLYXBYJK6FK7TC -O fx_job_invoke_script.sh
         chmod 755 fx_job_invoke_script.sh
         #cat fx_job_invoke_script.sh
         #./fx_job_invoke_script.sh ${USERNAME} ${PASSWORD} ${JOBID} ${REGION} ${ENVIRONMENTID} ${PROJECTID}
      env:
        USERNAME: "mohd@apisec.ai"
        PASSWWORD: "Raasta@123!"
        JOBID: "8a80818a7ae6a306017ae7597a520e81"
        REGION: "Super_1"
        ENVIRONMENTID: "8a80818a7ae6a306017ae7598caf1002"
        PROJECTID: "8a8084847b1f49cf017b3cdcb0f700fc"
      shell: bash      
    - run: ${{ github.action_path }}/goodbye.sh ${{ inputs.GREET }}
#      env:
#        GREET: ${GREET}
      shell: bash


# name: 'Hello World654'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:    
#   using: "composite"
#   steps:
#     - run: echo "Welcome to github actions"
#       shell: bash    
#       run: pwd
#       shell: bash
#     - run: ls -ll
#       shell: bash


